spring.application.name=TechnicalSupportMS
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/catchop_support_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


textrazor.api.key=YOUR_TEXTRAZOR_API_KEY


summarization.api.url=http://localhost:5000/summarize

# SLA settings (hours)
support.sla.low=72
support.sla.medium=48
support.sla.high=24
support.sla.critical=4

# Scheduler: run every hour
support.scheduler.cron=0 0 * * * *
