pipeline {
    agent any

    environment {
        DOCKER_USER   = 'bunnybanou'
        IMAGE_NAME    = 'bunnybanou/catchopp-user'
        SONARQUBE_URL = 'http://localhost:9000'
    }

    tools {
        jdk 'jdk'
        maven 'mvn'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'gestion_sub',
                    url: 'https://github.com/Hchaichi8/CATCHOPP.git'
            }
        }

        stage('Build Maven') {
            steps {
                dir('CATCHOPP/CatchOPP/UserMicroService') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('CATCHOPP/CatchOPP/SkillTestsMicroService') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'CATCHOPP/CatchOPP/SkillTestsMicroService/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('CATCHOPP/CatchOPP/UserMicroService') {
                    withCredentials([string(credentialsId: 'sonar_pi', variable: 'SONAR_TOKEN')]) {
                        sh """
                            mvn sonar:sonar \
                            -Dsonar.projectKey=catchopp-user-service \
                            -Dsonar.projectName='CatchOPP UserMicroService' \
                            -Dsonar.host.url=${SONARQUBE_URL} \
                            -Dsonar.login=${SONAR_TOKEN} \
                            -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CATCHOPP/CatchOPP/UserMicroService') {
                    sh 'docker build -t bunnybanou/catchopp-user:latest .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'TokenDevOps',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push bunnybanou/catchopp-user:latest
                        docker logout
                    '''
                }
            }
        }

    }

    post {
        success {
            echo '✅ Build, SonarQube analysis and push successful!'
        }
        failure {
            echo '❌ Build failed. Check the logs.'
        }
    }
}
